# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\MyProgram\Software\OpenSeesMaterialTest\ui\WinHelp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WinHelp(object):
    def setupUi(self, WinHelp):
        WinHelp.setObjectName("WinHelp")
        WinHelp.resize(615, 713)
        WinHelp.setMinimumSize(QtCore.QSize(422, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        WinHelp.setFont(font)
        WinHelp.setWindowTitle("帮助文档")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("f:\\MyProgram\\Software\\OpenSeesMaterialTest\\ui\\../logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WinHelp.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(WinHelp)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(WinHelp)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 595, 655))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_2.addWidget(self.textBrowser)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(WinHelp)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)

        self.retranslateUi(WinHelp)
        self.pushButton.clicked.connect(WinHelp.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(WinHelp)

    def retranslateUi(self, WinHelp):
        _translate = QtCore.QCoreApplication.translate
        self.textBrowser.setHtml(_translate("WinHelp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\',\'微软雅黑\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:26pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:26pt;\">OpenSees材料测试程序</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:26pt;\">帮助文档</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:26pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-weight:600;\">1 功能介绍</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:600;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">    该程序可用于测试OpenSees中单轴材料的滞回行为，所支持的材料包括OpenSeesPy3.5.1.3中的所有位移相关型单轴材料，暂不支持多轴材料和速度相关型材料（如Maxwell材料等）。</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:16pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-weight:600;\">2. 使用方法</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:600;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:600;\">（1）导入试验滞回曲线（可选）</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">    首先点击导入试验滞回曲线，选择包含试验数据的.txt文件，应注意.txt文件中应只包含两列数据，依次为位移数据和力数据，否则程序无法顺利读取。若不导入试验滞回曲线，则在最终绘制滞回曲线时将不会包含试验结果。</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:600;\">（2）定义材料</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">    材料的定义方式与在tcl或python中的定义类似，输入材料的参数即可，OpenSees材料参数可在</span><a href=\"https://openseespydoc.readthedocs.io/en/latest/src/uniaxialMaterial.html\"><span style=\" font-family:\'SimSun\'; font-size:16pt; text-decoration: underline; color:#0000ff;\">openseespy</span></a><span style=\" font-family:\'SimSun\'; font-size:16pt;\">官网的单轴材料页面查询。以Steel01材料为例，首先输入材料名（即“Steel01”），在官网可查得Steel01材料在OpenSeesPy（python）中的定义方式为：</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt; color:#0000ff;\">uniaxialMaterial(\'Steel01\', matTag, Fy, E0, b, a1, a2, a3, a4)</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">以此为参照，点击输入材料参数，在弹出的表格中输入除了材料名（Steel01）和材料编号（matTag）之外的其余参数即可，应注意输入顺序应保持一致，对于可选参数（a1-a4）可以不输入。更多的材料信息还可在</span><a href=\"https://opensees.berkeley.edu/wiki/index.php/UniaxialMaterial_Command\"><span style=\" font-family:\'SimSun\'; font-size:16pt; text-decoration: underline; color:#0000ff;\">OpenSees</span></a><span style=\" font-family:\'SimSun\'; font-size:16pt;\">官网查询。</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:600;\">（3）生成加载制度</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">    在绘制滞回曲线前，应确定加载制度（即输入计算的位移），在程序中可选择采用试验滞回曲线的位移数据（应首先导入试验滞回曲线）或自定义加载制度。若自定义加载制度，用户需输入位移的反向点（如0、5、0、-5、0、20、0、-20、0），并给定最小位移增量，程序会自动生成位移数据，并令相邻点的位移间隔不小于用户给定的最小位移增量，以保证位移数据具有足够密度。点击生成加载制度按钮，程序会绘制加载制度曲线图，应注意每次更改加载制度后需重新点击生成加载制度以进行刷新。</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:600;\">（4）绘制滞回曲线</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:16pt;\">    点击绘制滞回曲线按钮，程序会调用openseespy求解器进行计算，计算完成会将结果进行绘制。若用户有导入试验滞回曲线，则程序会同时绘制试验结果及opensees材料的计算结果以方便进行对比，若没有导入试验滞回曲线，则只会绘制计算结果。用户可以点击数据按钮查看计算结果，并进行复制或导出至.txt文件中。</span></p></body></html>"))
        self.pushButton.setText(_translate("WinHelp", "确认"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WinHelp = QtWidgets.QWidget()
    ui = Ui_WinHelp()
    ui.setupUi(WinHelp)
    WinHelp.show()
    sys.exit(app.exec_())
