# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\MyProgram\Software\OpenSeesMaterialTest\ui\WinOSPara.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WinOSPara(object):
    def setupUi(self, WinOSPara):
        WinOSPara.setObjectName("WinOSPara")
        WinOSPara.resize(318, 529)
        WinOSPara.setMinimumSize(QtCore.QSize(318, 500))
        WinOSPara.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        WinOSPara.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("f:\\MyProgram\\Software\\OpenSeesMaterialTest\\ui\\../logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WinOSPara.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(WinOSPara)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(WinOSPara)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.table = QtWidgets.QTableWidget(WinOSPara)
        self.table.setMinimumSize(QtCore.QSize(150, 0))
        self.table.setMouseTracking(False)
        self.table.setFrameShape(QtWidgets.QFrame.Box)
        self.table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.table.setRowCount(99)
        self.table.setColumnCount(1)
        self.table.setObjectName("table")
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        self.table.horizontalHeader().setVisible(True)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setDefaultSectionSize(250)
        self.table.horizontalHeader().setSortIndicatorShown(False)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.verticalHeader().setVisible(True)
        self.table.verticalHeader().setCascadingSectionResizes(False)
        self.table.verticalHeader().setDefaultSectionSize(30)
        self.table.verticalHeader().setHighlightSections(True)
        self.table.verticalHeader().setMinimumSectionSize(30)
        self.table.verticalHeader().setSortIndicatorShown(False)
        self.table.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(WinOSPara)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(WinOSPara)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(WinOSPara)
        self.pushButton.clicked.connect(self.table.clearContents) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(WinOSPara)

    def retranslateUi(self, WinOSPara):
        _translate = QtCore.QCoreApplication.translate
        WinOSPara.setWindowTitle(_translate("WinOSPara", "OpenSees材料参数"))
        self.label_2.setText(_translate("WinOSPara", "输入材料参数:"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("WinOSPara", "1"))
        self.pushButton_2.setText(_translate("WinOSPara", "确认"))
        self.pushButton.setText(_translate("WinOSPara", "清空"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WinOSPara = QtWidgets.QDialog()
    ui = Ui_WinOSPara()
    ui.setupUi(WinOSPara)
    WinOSPara.show()
    sys.exit(app.exec_())
